# Generated by Django 5.2 on 2025-04-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_userscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscore',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userscore',
            name='streak_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
