# Generated by Django 5.2 on 2025-04-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pollquestion_polloption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollquestion',
            old_name='question_text',
            new_name='question',
        ),
    ]
